export { BaseComponent } from './base-component';
export type { IBaseComponent } from './i-base-component';
export { BasePage } from './base-page';
export type { IBasePage } from './i-base-page';
export { register } from './register';
export type { IAwareEvent } from './aware/i-aware-event';
export { AwareComponentService } from './aware/aware-component-service';
export { DIAwareComponentService, type IAwareComponentService } from './aware/i-aware-component-service';
export type { ICustomElementAware } from './aware/i-custom-element-aware';
export { AwareComponent } from './aware/aware-component';
export { DIStoreService, type IStoreService, type StoreKey, type StoreLoadOptions } from './store/i-store-service';
export { StoreService } from './store/store-service';
export type { IStoreMessenger } from './store/i-store-messenger';
export { type DebugContainerStats, ResolverStrategyMap, debugContainer } from './container/au2-di-debugger';
export { defaultCapture } from './common/default-capture';
