name: Release CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      # - name: Use Node.js ${{ matrix.node-version }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@aegenet'

      - name: Root dependencies
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm i
      - name: Install dependencies
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm run dependencies

      - name: Lint
        run: npm run lint
      - name: Set version
        run: npm run version
      - name: Build
        run: npm run build
      - name: Tests
        run: npm run test:coverage

      - name: Publish packages GitHub
        env:
          CI: true
          YAWT_NPM_PUBLIC_PUBLISH: 'false'
          YAWT_NPM_NAMESPACE: '@aegenet'
          YAWT_NPM_PUSH_REGISTRY: https://npm.pkg.github.com/
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm run publish

      - name: Publish packages npm
        env:
          CI: true
          YAWT_NPM_PUBLIC_PUBLISH: 'true'
          YAWT_NPM_NAMESPACE: '@aegenet'
          YAWT_NPM_PUSH_REGISTRY: https://registry.npmjs.org/
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npm run publish

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
